a=input("Masukkan nilai a : ")
b=input("Masukkan nilai b : ")
print("Variabel a = ",a)
print("Variabel b = ",b)
print("Hasil Penggabungan {0} & {1} = {2}".format(a,b,a+b))
print("Konversi Nilai Variabel")
a=int(a)
b=int(b)
print("Hasil Penjumlahan {0} & {1} = {2}".format(a,b,a+b))
print("Hasil Pembagian {0} & {1} = {2}".format(a,b,a/b))